### ISSUE TITLE
easemob出现协商失败的问题

### ISSUE THREAD

**Issue by jlshix** [lizhangqu/VoiceAndVideo#1]
在使用easemob的demo时无法接受视频通话请求,在logcat中可以看到已经接收到请求,但是不能跳转到VideoCallActivity, 在logcat中显示以下问题:
- D/EMReceiverJingleSession: callee is null when free ice
- D/EMVoiceCallSession: negotiation complete, result: {"result":-1}
- D/EMVoiceCallSession: close sesstion, state: NEGOTIATING_TRANSPORT
- D/EMVoiceCallSession: negotiation fails
- D/EMVoiceCallManager: onCallStateChanged with callState = disconnected callError = error_none
- D/EMReceiverJingleSession: callee is null when free ice

**Comment by shenwenbin123** [comment]
遇到与楼上同样的问题
